import { FinishReason, GoogleGenAI, JobState, ThinkingLevel } from "@google/genai";
import type { DraftContent, DraftPost, PendingDraft, SourceCheck } from "./draftStore";

/**
 * Weekly AI-voice-agent news draft, generated by Gemini with Google Search
 * grounding and returned as a validated JSON object.
 *
 * Three design decisions carry the whole feature:
 *
 * 1. THE BATCH API, not a normal request. Researching a week of news and
 *    writing it up bilingually takes minutes, and this project's serverless
 *    functions cap at 60s. A batch is asynchronous by construction — submit
 *    now, collect whenever — so the cron never races a timeout. It is also
 *    half price, which matters for something that runs unattended forever.
 *
 * 2. GROUNDING WITH GOOGLE SEARCH, not a news API or the model's memory. A
 *    model writing "news" from training data invents it — that is the failure
 *    mode that makes auto-published news dangerous. Grounding runs the search
 *    on Google's infrastructure, so the draft is anchored to pages that
 *    actually exist.
 *
 * 3. SOURCE VERIFICATION FROM METADATA, not from the model's own account of
 *    its work. See groundedSources() below — this is the part that stops a
 *    confidently-cited page that was never opened from reaching the site.
 *
 * Nothing here publishes. The output is a draft for a human to read.
 */

export const MODEL = "gemini-3.6-flash";

/**
 * Ungrounded research is resubmitted up to this many times before giving up.
 *
 * Measured search rate is roughly 1 in 4, so 5 attempts only reaches ~76%
 * success — for a weekly job that is a missed post every month. At 8 it is
 * ~90%. Each attempt is a cheap research batch, and the alternative (writing
 * from memory) is not on the table, so the cap is set by reliability rather
 * than cost.
 */
const MAX_RESEARCH_ATTEMPTS = 8;

/**
 * Plain JSON Schema, deliberately narrow: Gemini's `responseJsonSchema`
 * supports a subset of the spec, and unsupported keywords are the usual cause
 * of a confusing 400. In particular there is no `additionalProperties` here —
 * that was an Anthropic structured-output requirement, and carrying it over
 * is what breaks the request.
 *
 * `propertyOrdering` is a Gemini extension. It matters for quality as well as
 * shape: the model generates keys in this order, so it writes the content
 * before it writes the source list.
 */
const BLOCK_SCHEMA = {
  type: "object",
  properties: {
    t: { type: "string", enum: ["p", "h2", "ul", "ol", "note"] },
    text: { type: "string" },
    items: { type: "array", items: { type: "string" } },
  },
  required: ["t"],
  propertyOrdering: ["t", "text", "items"],
} as const;

const STR = { type: "string" } as const;

/**
 * FLAT ON THE WIRE. The obvious shape — `{ ar: {title, body[…]}, en: {…} }` —
 * is rejected by the Batch API, and this is the single hardest-won fact in
 * this file.
 *
 * The batch schema validator is far stricter than the synchronous one: it
 * accepts only about TWO levels of nested objects, where models.generateContent
 * accepts five without complaint. The nested form is root → ar → body → block,
 * which is three, so every batch request died with a bare "Request contains an
 * invalid argument" naming no field, while the identical schema worked
 * perfectly in a normal call.
 *
 * Established by five rounds of probing (see api/cron/batch-probe): every
 * individual feature passes; the schema minus its ar/en branches passes; ONE
 * branch fails exactly like two, so it is depth and not size; and this hoisted
 * form passes even combined with search, thinking and 32k output tokens.
 *
 * Arrays of scalars cost nothing — only nested OBJECTS count — so `ar_body`
 * keeps its block objects and `tags` keeps its one nested level.
 *
 * Nothing downstream sees this shape: nest() converts it straight back to the
 * nested DraftPost the review page and content file already use.
 */
export const DRAFT_SCHEMA = {
  type: "object",
  properties: {
    slug: STR,
    tags: {
      type: "object",
      properties: {
        ar: { type: "array", items: STR },
        en: { type: "array", items: STR },
      },
      required: ["ar", "en"],
    },
    ar_title: STR,
    ar_description: STR,
    ar_excerpt: STR,
    ar_body: { type: "array", items: BLOCK_SCHEMA },
    en_title: STR,
    en_description: STR,
    en_excerpt: STR,
    en_body: { type: "array", items: BLOCK_SCHEMA },
  },
  required: [
    "slug",
    "tags",
    "ar_title",
    "ar_description",
    "ar_excerpt",
    "ar_body",
    "en_title",
    "en_description",
    "en_excerpt",
    "en_body",
  ],
  // Root-level only, and purely for generation order: the post is written
  // before the source list. Proven harmless in batch (a nested schema with
  // propertyOrdering passes; depth is what fails).
  propertyOrdering: [
    "slug",
    "tags",
    "ar_title",
    "ar_description",
    "ar_excerpt",
    "ar_body",
    "en_title",
    "en_description",
    "en_excerpt",
    "en_body",
  ],
} as const;

/** The flat object the model returns, before nest() reshapes it. */
interface FlatDraft {
  slug: string;
  tags: { ar: string[]; en: string[] };
  ar_title: string;
  ar_description: string;
  ar_excerpt: string;
  ar_body: DraftContent["body"];
  en_title: string;
  en_description: string;
  en_excerpt: string;
  en_body: DraftContent["body"];
}

/**
 * Validate the model's output ourselves.
 *
 * `responseJsonSchema` does NOT strictly enforce `required` — this has now bitten
 * twice: `sources` entries arrived with no `url`, and `ar_body`/`en_body` arrived
 * as something other than an array, which 500'd the review page for every draft
 * in the queue. The schema is a strong hint to the model, not a guarantee to us.
 *
 * Returns null when the shape is usable, or a human-readable reason when it is
 * not, so the draft is rejected at collection rather than poisoning the queue.
 */
function invalidReason(flat: FlatDraft): string | null {
  const text = (v: unknown, name: string) =>
    typeof v === "string" && v.trim().length > 0 ? null : `${name} missing or not a string`;

  const blocks = (v: unknown, name: string) => {
    if (!Array.isArray(v) || v.length === 0) return `${name} missing or not an array`;
    const bad = v.find(
      (b) => !b || typeof b !== "object" || typeof (b as { t?: unknown }).t !== "string",
    );
    return bad ? `${name} contains a block with no type` : null;
  };

  return (
    text(flat.slug, "slug") ??
    text(flat.ar_title, "ar_title") ??
    text(flat.en_title, "en_title") ??
    text(flat.ar_description, "ar_description") ??
    text(flat.en_description, "en_description") ??
    blocks(flat.ar_body, "ar_body") ??
    blocks(flat.en_body, "en_body") ??
    (Array.isArray(flat.tags?.ar) && Array.isArray(flat.tags?.en) ? null : "tags missing")
  );
}

/** Flat wire shape → the nested shape the rest of the app already speaks. */
function nest(flat: FlatDraft): Omit<DraftPost, "generatedAt" | "sources"> {
  return {
    slug: flat.slug,
    tags: flat.tags,
    ar: {
      title: flat.ar_title,
      description: flat.ar_description,
      excerpt: flat.ar_excerpt,
      body: flat.ar_body,
    },
    en: {
      title: flat.en_title,
      description: flat.en_description,
      excerpt: flat.en_excerpt,
      body: flat.en_body,
    },
  };
}

/**
 * TWO CALLS, and the split is not optional.
 *
 * Combining Google Search grounding with a response schema returns EMPTY
 * grounding metadata. Measured on this account: identical prompt and identical
 * search tool, one with a schema and one without — the schema-less call came
 * back with grounding chunks, the schema'd call came back with none.
 *
 * Grounding metadata is where the real source URLs live, so a single grounded
 * + structured call would grade every source UNVERIFIED forever. That is worse
 * than no check: a weekly wall of red teaches the reviewer to ignore it.
 *
 * So: research WITH search and NO schema (keeps the metadata), then structure
 * WITH schema and NO search (needs no web access at all).
 */
export const RESEARCH_PROMPT = `SEARCH THE WEB FIRST. Do not answer from memory — anything not found in search results this session is unusable and will be discarded.

Run at least eight web searches now, in both Arabic and English, on: AI voice agents, conversational AI, contact-centre automation, Saudi/Gulf market news, and notable global news. Cover the past 7 days.

Then write research NOTES (plain text, not an article) for the blog of Saut Najdi — a Saudi company selling a hybrid AI + human call-centre agent answering calls in Saudi dialects. The audience is Saudi business buyers.

For each item: what happened, and why a Saudi business buyer should care.

Rules:
- Only report what you found in the search results. If a search week is thin, say so instead of padding.
- Never invent a company, funding round, product launch, statistic, date or quote.
- Quote no more than a short phrase from any source.
- Make no claims about Saut Najdi's own product, customers or performance.
- Label anything unconfirmed as a rumour.`;

/**
 * Second call. No search tool, so the schema is safe to use here — and there
 * is no grounding metadata to lose, because the sources were already captured
 * by the research call.
 */
export const STRUCTURE_PROMPT = `Turn the research notes below into ONE blog post in both Arabic and English, as a single JSON object matching the required schema.

Use ONLY facts present in the notes. Do not add, extrapolate, or embellish. Do not search — you have no web access.

- Arabic is the primary language. Use natural Saudi business Arabic, not stiff Modern Standard Arabic. Match the register of a knowledgeable colleague briefing you.
- The two languages must carry the same facts. The English is not a literal translation — write it natively.
- The JSON is FLAT: Arabic fields are ar_title / ar_description / ar_excerpt / ar_body, English are en_title / en_description / en_excerpt / en_body. Two languages of the SAME post, not two posts.
- slug: lowercase Latin, hyphenated, dated, e.g. "ai-voice-news-2026-08-17". No Arabic in the slug.
- ar_title / en_title: under 47 characters — a site-name suffix is appended later and the total budget is 60.
- ar_description / en_description: 70-160 characters.
- ar_excerpt / en_excerpt: one sentence for the listing card.
- ar_body / en_body: 400-700 words each. Use "h2" for sections, "p" for prose, "ul"/"ol" for lists, "note" for a caveat. Lead with what matters to a Saudi buyer.
- Do NOT output a sources list. Citations are attached automatically from the pages that were actually retrieved, so any you invented would be discarded anyway.

RESEARCH NOTES:
`;

function client(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  // Explicit rather than relying on the SDK's env lookup, so a missing key
  // fails here with a readable message instead of as a 401 a day later.
  if (!apiKey) throw new Error("GEMINI_API_KEY is not set");
  return new GoogleGenAI({ apiKey });
}

/** Submits the batch job. Returns the job name ("batches/…") to poll later. */
export async function submitDraftBatch(): Promise<string> {
  const job = await client().batches.create({
    model: MODEL,
    src: [
      {
        // No `model` here on purpose: it belongs on the batch (and goes into
        // the request URL), and this matches the exact inlined-request shape
        // proven to work by the probe. It was briefly added on a mistaken
        // theory about the failure; the real cause was schema depth, above.
        contents: [{ role: "user", parts: [{ text: RESEARCH_PROMPT }] }],
        config: {
          tools: [{ googleSearch: {} }],
          // NO responseJsonSchema here — see the note on RESEARCH_PROMPT. A
          // schema on this call silently empties the grounding metadata, which
          // is the whole basis of source verification.
          thinkingConfig: { thinkingLevel: ThinkingLevel.HIGH },
          maxOutputTokens: 32768,
        },
      },
    ],
    config: { displayName: "weekly-news-draft" },
  });
  if (!job.name) throw new Error("batch created without a name");
  return job.name;
}

export type CollectResult =
  | { status: "pending" }
  | { status: "failed"; reason: string }
  /** Research finished; the write-up batch has been submitted as `next`. */
  | { status: "advanced"; next: PendingDraft }
  | { status: "ready"; draft: DraftPost };

const FINISHED = new Set<string>([
  JobState.JOB_STATE_SUCCEEDED,
  JobState.JOB_STATE_FAILED,
  JobState.JOB_STATE_CANCELLED,
  JobState.JOB_STATE_EXPIRED,
  JobState.JOB_STATE_PARTIALLY_SUCCEEDED,
]);

/** Answer text only: thought parts are reasoning, and folding them in corrupts the output. */
function textOf(candidate: { content?: { parts?: { text?: string; thought?: boolean }[] } }): string {
  return (candidate.content?.parts ?? [])
    .filter((p) => !p.thought && typeof p.text === "string")
    .map((p) => p.text)
    .join("");
}

/**
 * Turn research notes into the structured post — SYNCHRONOUSLY, on purpose.
 *
 * This step ran as a second batch for a while, and that broke the writer:
 * every batch run produced structurally invalid output (`ar_body` missing,
 * sources without urls) while the identical call via models.generateContent
 * produced a perfectly-shaped draft. The pattern in the failure log makes the
 * cause plain: THE BATCH API DOES NOT ENFORCE responseJsonSchema ON OUTPUT —
 * it treats the schema as a hint. The synchronous endpoint does constrained
 * decoding, so the shape is guaranteed.
 *
 * The 60s function limit is not a problem here: this is transcription of notes
 * already gathered — no search, MINIMAL thinking — and it completed well
 * within the limit when it ran this way before. Research, the genuinely slow
 * half, stays in batch.
 */
async function structureNow(notes: string, grounded: Grounded): Promise<CollectResult> {
  let response;
  try {
    response = await client().models.generateContent({
      model: MODEL,
      contents: `${STRUCTURE_PROMPT}${notes}`,
      config: {
        responseMimeType: "application/json",
        responseJsonSchema: DRAFT_SCHEMA,
        thinkingConfig: { thinkingLevel: ThinkingLevel.MINIMAL },
        maxOutputTokens: 32768,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { status: "failed", reason: `structuring call failed: ${message.slice(0, 200)}` };
  }

  const candidate = response.candidates?.[0];
  if (!candidate) return { status: "failed", reason: "structuring returned no candidate" };
  if (candidate.finishReason && candidate.finishReason !== FinishReason.STOP) {
    return { status: "failed", reason: `structuring finished as ${candidate.finishReason}` };
  }
  const text = textOf(candidate);
  if (!text.trim()) return { status: "failed", reason: "structuring returned no text" };

  return finishDraft(text, grounded);
}

/**
 * Polls one batch and moves the draft along one stage.
 *
 * research  -> reads grounding metadata, submits the write-up batch ("advanced")
 * structure -> parses the post and grades every cited source ("ready")
 */
export async function collectDraftBatch(pending: PendingDraft): Promise<CollectResult> {
  const job = await client().batches.get({ name: pending.batchId });
  if (!job.state || !FINISHED.has(job.state)) return { status: "pending" };
  if (job.state !== JobState.JOB_STATE_SUCCEEDED) {
    return { status: "failed", reason: `batch ${job.state}` };
  }

  const [entry] = job.dest?.inlinedResponses ?? [];
  if (!entry) return { status: "failed", reason: "batch ended with no results" };
  if (entry.error) {
    return { status: "failed", reason: `request error: ${entry.error.message ?? "unknown"}` };
  }

  const candidate = entry.response?.candidates?.[0];
  if (!candidate) return { status: "failed", reason: "no candidate in response" };

  // MAX_TOKENS means output is cut off mid-object; the rest mean no usable
  // content. Either way it must not reach the queue as a draft.
  const finish = candidate.finishReason;
  if (finish && finish !== FinishReason.STOP) {
    return { status: "failed", reason: `finished as ${finish}` };
  }

  const text = textOf(candidate);
  if (!text.trim()) return { status: "failed", reason: "no text in response" };

  const stage = pending.stage ?? "research";

  if (stage === "research") {
    const chunks = candidate.groundingMetadata?.groundingChunks ?? [];
    const grounded = await groundedSources(chunks);
    // Logged because an empty grounding set silently degrades every source to
    // unverified, and that is invisible from the finished draft alone.
    console.log(
      "[draft-research]",
      JSON.stringify({
        chunks: chunks.length,
        resolvedUrls: grounded.urls.size,
        domains: [...grounded.domains].slice(0, 12),
      }),
    );
    /**
     * FAIL CLOSED when nothing was retrieved.
     *
     * `googleSearch` is a tool the model MAY call, not a guarantee that it
     * will. Identical configs have returned anywhere from 1 to 21 chunks, and
     * one real run returned zero — yet still produced a confident, fully
     * cited article. Every figure in it was unattributable.
     *
     * Zero chunks means the post would be written from training data with
     * invented citations, which is precisely what this feature exists to
     * prevent. Refusing here is the difference between a missed week and a
     * fabricated funding round published under the brand.
     */
    if (chunks.length === 0) {
      /**
       * RETRY, don't publish from memory.
       *
       * `googleSearch` is a tool the model MAY call, not a guarantee. Measured
       * across 12 real jobs: 3 searched (15-18 chunks), 9 did not — and the
       * ones that did not still produced confident, fully-cited articles whose
       * every figure was unattributable. That is exactly the failure this
       * feature exists to prevent.
       *
       * One attempt a week at ~25% would mean mostly no post, so an ungrounded
       * result resubmits instead of failing. The cap keeps a persistently
       * broken week from looping — at that point it fails loudly, which is the
       * correct end state.
       */
      const attempt = (pending.attempt ?? 1) + 1;
      if (attempt > MAX_RESEARCH_ATTEMPTS) {
        return {
          status: "failed",
          reason: `research returned no grounding after ${MAX_RESEARCH_ATTEMPTS} attempts — the model did not search. Refusing to draft from memory.`,
        };
      }
      console.log("[draft-research]", JSON.stringify({ retrying: attempt }));
      return {
        status: "advanced",
        next: {
          batchId: await submitDraftBatch(),
          submittedAt: new Date().toISOString(),
          stage: "research",
          attempt,
        },
      };
    }

    // Write-up runs synchronously in this same invocation — see structureNow.
    return structureNow(text, grounded);
  }

  // A structure-stage batch from before the sync revert may still be in
  // flight; collect it through the same finishing logic. New work never
  // submits one.
  return finishDraft(text, {
    urls: new Set(pending.grounded?.urls ?? []),
    domains: new Set(pending.grounded?.domains ?? []),
    pages: pending.grounded?.pages ?? [],
  });
}

/** Parse, validate, attach retrieval-built citations, and hand back a draft. */
async function finishDraft(text: string, grounded: Grounded): Promise<CollectResult> {
  let parsed: Omit<DraftPost, "generatedAt" | "sources">;
  let flatParsed: FlatDraft;
  try {
    // FLAT wire shape (kept so the sync and any legacy batch output match);
    // nest() restores the nested shape so nothing downstream knows.
    flatParsed = JSON.parse(text) as FlatDraft;
    parsed = nest(flatParsed);
  } catch {
    return { status: "failed", reason: "structured response was not valid JSON" };
  }

  const invalid = invalidReason(flatParsed);
  if (invalid) return { status: "failed", reason: `malformed draft: ${invalid}` };

  /**
   * CITATIONS COME FROM RETRIEVAL, NOT FROM THE MODEL.
   *
   * Asking the model to list its sources failed completely: eight citations
   * came back with titles and NO url. That is not laziness — when Gemini uses
   * grounding, citations live in the response METADATA, not in its prose, so
   * the research notes the write-up copied from had no URLs in them to copy.
   *
   * Building the list from the pages grounding actually fetched removes the
   * model from the citation loop entirely. Every entry is a page that was
   * genuinely retrieved, which is a stronger guarantee than any check applied
   * after the fact — a fabricated citation can no longer exist by construction.
   */
  const sources = await Promise.all(
    grounded.pages.map(async (page) => {
      const probe = await describe(page.url);
      return {
        title: probe.title ?? page.title,
        url: page.url,
        // Retrieved by grounding by definition. "dead" only if the page has
        // since stopped resolving, which is worth surfacing on its own.
        check: (probe.live ? "url" : "dead") as SourceCheck,
      };
    }),
  );

  console.log(
    "[draft-verify]",
    JSON.stringify({
      citedFromGrounding: sources.length,
      dead: sources.filter((s) => s.check === "dead").length,
      sample: sources.slice(0, 3).map((s) => s.url.slice(0, 80)),
    }),
  );

  if (sources.length === 0) {
    return { status: "failed", reason: "no retrievable sources — refusing to publish an uncited post" };
  }

  return {
    status: "ready",
    draft: { ...parsed, sources, generatedAt: new Date().toISOString() },
  };
}

/* ------------------------------------------------------------------ *
 * Source verification
 * ------------------------------------------------------------------ */

interface Grounded {
  /** Normalised "host/path" of every page grounding actually retrieved. */
  urls: Set<string>;
  /** Bare hostnames, used as the weaker fallback when a URL cannot be resolved. */
  domains: Set<string>;
  /** The real, resolved pages — this is what becomes the citation list. */
  pages: { url: string; title: string }[];
}

/**
 * Gemini does NOT hand back the URLs it read. `groundingChunks[].web.uri` is a
 * vertexaisearch.cloud.google.com redirect, and `.web.title` is only a domain
 * ("aljazeera"); the `.web.domain` field is Vertex-only and always empty here.
 * Compared against Anthropic's search-result blocks, which carried the real
 * URL, that is a genuine loss of fidelity in the one check this feature exists
 * for — so rather than accept it, each redirect is resolved back to its target
 * with a single un-followed request, reading the Location header.
 *
 * Nothing is fetched from the publisher itself: `redirect: "manual"` stops at
 * Google's hop. A failure to resolve degrades to domain matching rather than
 * throwing, and a domain match is reported honestly as the weaker result it is.
 */
async function groundedSources(
  chunks: { web?: { uri?: string; title?: string } }[],
): Promise<Grounded> {
  const urls = new Set<string>();
  const domains = new Set<string>();
  const pages: { url: string; title: string }[] = [];

  await Promise.all(
    chunks.map(async (chunk) => {
      const title = chunk.web?.title?.trim().toLowerCase().replace(/^www\./, "");
      if (title) domains.add(title);

      const uri = chunk.web?.uri;
      if (!uri) return;

      const target = hostOf(uri)?.endsWith("cloud.google.com") ? await followOnce(uri) : uri;
      if (!target) return;

      const normalised = normalise(target);
      if (normalised) urls.add(normalised);
      const host = hostOf(target);
      if (host) domains.add(host);
      if (/^https?:\/\//.test(target)) pages.push({ url: target, title: title ?? host ?? target });
    }),
  );

  // Same article can be retrieved more than once; cite it once.
  const seen = new Set<string>();
  const unique = pages.filter((p) => (seen.has(p.url) ? false : (seen.add(p.url), true)));

  return { urls, domains, pages: unique };
}

/** One hop, no body, short timeout. Never throws — an unresolved chunk is a downgrade, not an error. */
async function followOnce(uri: string): Promise<string | null> {
  try {
    const response = await fetch(uri, {
      redirect: "manual",
      signal: AbortSignal.timeout(6000),
    });
    return response.headers.get("location");
  } catch {
    return null;
  }
}

function hostOf(raw: string): string | null {
  try {
    return new URL(raw).hostname.toLowerCase().replace(/^www\./, "");
  } catch {
    return null;
  }
}

/** Host + path, lowercased, without "www." or a trailing slash. Query and fragment are dropped so the same article matches across tracking parameters. */
function normalise(raw: string): string | null {
  try {
    const url = new URL(raw);
    return `${url.hostname.toLowerCase().replace(/^www\./, "")}${url.pathname.replace(/\/+$/, "")}`;
  } catch {
    return null;
  }
}

/**
 * One fetch per source: proves the page still resolves AND recovers its real
 * <title>. Grounding only gives a bare domain ("spa.gov.sa"), which makes a
 * useless citation list, and we are fetching anyway to confirm liveness.
 *
 * A bot-blocking 403 still proves the page exists, so anything short of 404 or
 * a network failure counts as live — the question is existence, not readability.
 */
async function describe(url: string): Promise<{ live: boolean; title: string | null }> {
  try {
    const response = await fetch(url, {
      redirect: "follow",
      signal: AbortSignal.timeout(8000),
      headers: { "user-agent": "Mozilla/5.0 (compatible; SautNajdiDraftCheck/1.0)" },
    });
    const live = response.status !== 404 && response.status < 500;
    if (!live) return { live, title: null };
    const html = (await response.text()).slice(0, 20000);
    const match = /<title[^>]*>([^<]{1,300})<\/title>/i.exec(html);
    const title = match?.[1]?.replace(/\s+/g, " ").trim();
    return { live, title: title && title.length > 3 ? title : null };
  } catch {
    return { live: false, title: null };
  }
}
